name: Publish on CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  JAVA_VERSION: 17
  MC_VERSION: 1.20.1
  RELEASE_NAME: Kingdom Keys
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "${{env.JAVA_VERSION}}"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Get version number
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: kk_version
        with:
          file: gradle.properties
          property: kk_version

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 242862
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: DrsqKwVw
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "${{env.RELEASE_NAME}} ${{steps.kk_version.outputs.kk_version}}"
          version: "${{steps.kk_version.outputs.kk_version}}-${{env.MC_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: forge
          game-versions: 1.20.1

          java: "${{env.JAVA_VERSION}}"
